"""Outfit Composer APIs.

These endpoints power the mannequin-less Outfit Composer in the frontend.
Every wardrobe item that can be composed (top / bottom / shoes / hat) has a
matching 1024x1024 transparent PNG generated by
:mod:`pipeline.composer.alignment` so the client can stack four same-size
layers without any per-item geometry.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from pipeline.composer.alignment import (
    aligned_path_for,
    aligned_relative_path,
    align_item,
    realign_all,
    resolve_composer_category,
)
from pipeline.composer.seed import seed_closet, wipe_closet
from pipeline.database.storage import (
    get_all_wardrobe_items,
    get_wardrobe_item,
    update_wardrobe_item_alignment,
)

router = APIRouter(prefix="/api/composer", tags=["Composer"])

# The 4 frontend categories map 1:1 to the composer alignment categories.
CATEGORY_ALIASES = {
    "hats": "hat",
    "hat": "hat",
    "tops": "top",
    "top": "top",
    "bottoms": "bottom",
    "bottom": "bottom",
    "shoes": "shoes",
    "shoe": "shoes",
}


def _ensure_aligned(item: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Return a serialisable item record with a guaranteed aligned PNG.

    If the cached file is missing or the DB row hasn't been migrated yet,
    re-run alignment on demand and persist the result.
    """
    item_id = str(item.get("id") or "")
    if not item_id:
        return None

    category = item.get("composer_category") or resolve_composer_category(
        item.get("garment_type") if isinstance(item.get("garment_type"), str) else None,
        item.get("subtype") if isinstance(item.get("subtype"), str) else None,
    )
    if not category:
        return None

    aligned_rel = item.get("aligned_image_path")
    aligned_abs = aligned_path_for(item_id)

    if not aligned_rel or not aligned_abs.exists():
        try:
            result = align_item({**item, "id": item_id})
        except Exception as exc:  # noqa: BLE001
            print(f"[composer] on-demand alignment failed for {item_id}: {exc}")
            return None
        if result is None:
            return None
        aligned_rel = aligned_relative_path(item_id)
        update_wardrobe_item_alignment(item_id, aligned_rel, category)

    return {
        "id": item_id,
        "category": category,
        "aligned_url": aligned_rel,
        "image_url": item.get("image_path"),
        "name": f"{item.get('brand') or 'Classic'} {item.get('subtype') or category}".strip(),
        "brand": item.get("brand"),
        "subtype": item.get("subtype"),
        "style": item.get("style"),
        "material": item.get("material"),
        "colors": item.get("colors", []),
        "tags": item.get("tags", []),
        "garment_type": item.get("garment_type"),
    }


@router.get("/category/{category}")
def list_category(category: str) -> Dict[str, Any]:
    """Returns every closet item that fits in the requested composer slot."""
    canonical = CATEGORY_ALIASES.get(category.lower())
    if not canonical:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown category {category!r}. Use one of: hats, tops, bottoms, shoes.",
        )

    items = get_all_wardrobe_items()
    composed: List[Dict[str, Any]] = []
    for item in items:
        target_cat = item.get("composer_category") or resolve_composer_category(
            item.get("garment_type") if isinstance(item.get("garment_type"), str) else None,
            item.get("subtype") if isinstance(item.get("subtype"), str) else None,
        )
        if target_cat != canonical:
            continue
        record = _ensure_aligned(item)
        if record is not None:
            composed.append(record)

    return {"category": canonical, "count": len(composed), "items": composed}


@router.get("/all")
def list_all_categories() -> Dict[str, Any]:
    """Convenience endpoint that returns all four category lists in one call."""
    items = get_all_wardrobe_items()
    buckets: Dict[str, List[Dict[str, Any]]] = {"hat": [], "top": [], "bottom": [], "shoes": []}
    for item in items:
        target_cat = item.get("composer_category") or resolve_composer_category(
            item.get("garment_type") if isinstance(item.get("garment_type"), str) else None,
            item.get("subtype") if isinstance(item.get("subtype"), str) else None,
        )
        if target_cat not in buckets:
            continue
        record = _ensure_aligned(item)
        if record is not None:
            buckets[target_cat].append(record)
    return {
        "hats": buckets["hat"],
        "tops": buckets["top"],
        "bottoms": buckets["bottom"],
        "shoes": buckets["shoes"],
    }


@router.post("/realign-all")
def realign_all_endpoint() -> Dict[str, Any]:
    """Regenerates the aligned PNG for every composable item in the closet."""
    return realign_all()


@router.post("/realign/{item_id}")
def realign_item(item_id: str) -> Dict[str, Any]:
    """Force-realigns a single item, useful after manual edits."""
    item = get_wardrobe_item(item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    result = align_item(item)
    if result is None:
        raise HTTPException(status_code=400, detail="Item is not composable (unsupported category or missing crop)")
    _, category = result
    rel = aligned_relative_path(item_id)
    update_wardrobe_item_alignment(item_id, rel, category)
    return {"id": item_id, "aligned_url": rel, "category": category}


class SeedRequest(BaseModel):
    """Body for :func:`seed_endpoint`."""

    per_category: int = 3
    wipe: bool = True
    remove_uploads: bool = False


class WipeRequest(BaseModel):
    """Body for :func:`wipe_endpoint`."""

    remove_uploads: bool = False


@router.post("/seed")
def seed_endpoint(request: Optional[SeedRequest] = None) -> Dict[str, Any]:
    """Wipe (optional) and generate a small Gemini-curated starter closet."""
    body = request or SeedRequest()
    per_cat = max(1, min(int(body.per_category), 5))
    return seed_closet(
        per_category=per_cat,
        wipe=bool(body.wipe),
        remove_uploads=bool(body.remove_uploads),
    )


@router.post("/wipe")
def wipe_endpoint(request: Optional[WipeRequest] = None) -> Dict[str, Any]:
    """Delete every wardrobe row and its crop / aligned PNG."""
    body = request or WipeRequest()
    return wipe_closet(remove_uploads=bool(body.remove_uploads))


class StylePromptRequest(BaseModel):
    prompt: Optional[str] = None


@router.post("/generate-style")
def generate_style(request: StylePromptRequest) -> Dict[str, Any]:
    """Coordinates a 4-layer outfit via the Gemini stylist.

    Accepts an optional free-form text prompt (e.g. "cyberpunk streetwear")
    that is forwarded to the AI stylist as additional context. Falls back to
    the offline rule engine when no API key is configured.
    """
    from pipeline.analysis.gemini_client import gemini_client

    items = get_all_wardrobe_items()
    result = gemini_client.generate_perfect_outfit(items, style_prompt=request.prompt or None)

    # Re-key the active_items dict by composer category and include the aligned
    # URLs so the client can render immediately without a second round-trip.
    active_items: Dict[str, Optional[str]] = result.get("active_items", {}) or {}
    layers: Dict[str, Optional[Dict[str, Any]]] = {"hat": None, "top": None, "bottom": None, "shoes": None}

    def _lookup(item_id: str) -> Optional[Dict[str, Any]]:
        if not item_id:
            return None
        item = get_wardrobe_item(item_id)
        if not item:
            return None
        return _ensure_aligned(item)

    # Map the existing taxonomy keys (top/bottom/shoes/outerwear/accessory)
    # back into the 4 composer slots.
    for key in ("top", "outerwear"):
        rec = _lookup(active_items.get(key, ""))
        if rec is not None and layers["top"] is None:
            layers["top"] = rec
    layers["bottom"] = _lookup(active_items.get("bottom", ""))
    layers["shoes"] = _lookup(active_items.get("shoes", ""))

    acc_rec = _lookup(active_items.get("accessory", ""))
    if acc_rec is not None and acc_rec.get("category") == "hat":
        layers["hat"] = acc_rec

    return {
        "style_name": result.get("style_name"),
        "explanation": result.get("explanation"),
        "prompt": request.prompt or None,
        "layers": layers,
        "raw": result,
    }
